export default {
    js: 'jsx',
    jsx: 'jsx',
    // TODO: add more
    // https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js
    //   markup: true,
    //   bash: true,
    //   clike: true,
    //   c: true,
    //   cpp: true,
    //   css: true,
    //   "css-extras": true,
    //   javascript: true,
    //   jsx: true,
    //   "js-extras": true,
    //   coffeescript: true,
    //   diff: true,
    //   git: true,
    //   go: true,
    //   graphql: true,
    //   handlebars: true,
    //   json: true,
    //   less: true,
    //   makefile: true,
    //   markdown: true,
    //   objectivec: true,
    //   ocaml: true,
    //   python: true,
    //   reason: true,
    //   sass: true,
    //   scss: true,
    //   sql: true,
    //   stylus: true,
    //   tsx: true,
    //   typescript: true,
    //   wasm: true,
    //   yaml: true,
};